title: Quantum Acorn
email: tom.jira@gmail.com
github_username: tjira

url: "https://tjira.github.io"
baseurl: "/acorn"

plugins:
  - jekyll-remote-theme

remote_theme: just-the-docs/just-the-docs

aux_links:
  "Quantum Acorn on GitHub":
    - "//github.com/tjira/acorn"

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
